PREFIX arp: <http://arp.ro/schema#>

SELECT DISTINCT ?artist ?name ?wikidataName
WHERE {
  ?artist a arp:Artist .

  OPTIONAL { ?artist arp:name ?name }
  OPTIONAL { ?artist arp:wikidataName ?wikidataName }
}
ORDER BY ?name