PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT ?title ?artwork
       (SAMPLE(?image) AS ?imageSample)
       ?sitelinks
WHERE {
  ?artwork wdt:P31 wd:Q838948 .
  ?artwork rdfs:label ?title FILTER(LANG(?title)="en")
  OPTIONAL { ?artwork wdt:P18 ?image }
  ?artwork wikibase:sitelinks ?sitelinks
}
GROUP BY ?title ?artwork ?sitelinks
ORDER BY DESC(?sitelinks)
LIMIT {{LIMIT}}
OFFSET {{OFFSET}}
