PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX mwapi: <https://www.mediawiki.org/ontology#API/>

SELECT ?item ?itemLabel ?image ?ulan WHERE {
  # Cautare Full-Text
  SERVICE wikibase:mwapi {
      bd:serviceParam wikibase:api "EntitySearch" .
      bd:serviceParam wikibase:endpoint "www.wikidata.org" .

      # %s va fi inlocuit de Java cu numele artistului (ex: "Nicolae Grigorescu")
      bd:serviceParam mwapi:search "%s" .

      bd:serviceParam mwapi:language "en" .
      ?item wikibase:apiOutputItem mwapi:item .
  }

  # Obtinem imaginea (optional)
  OPTIONAL { ?item wdt:P18 ?image. }

  # Obtinem ULAN ID (P245) - ID-ul Getty pentru Artisti
  OPTIONAL { ?item wdt:P245 ?ulan. }

  # Obtinem eticheta
  SERVICE wikibase:label { bd:serviceParam wikibase:language "ro,en,fr,de". }
}
LIMIT 1